In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Chronic kidney disease prediction.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,97,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,98,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,99,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,99,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
#it replaces 'yes' with 1 and 'no' with 0.
dataset['Possible'] = dataset['Possible'].replace(['yes','no'], [1,0])

In [5]:
dictonary = {
        "rbc": {
        "abnormal":1,
        "normal": 0,
    },
        "pc":{
        "abnormal":1,
        "normal": 0,
    },
        "pcc":{
        "present":1,
        "notpresent":0,
    },
        "ba":{
        "notpresent":0,
        "present": 1,
    },
        "htn":{
        "yes":1,
        "no": 0,
    },
        "dm":{
        "yes":1,
        "no":0,
    },
        "cad":{
        "yes":1,
        "no": 0,
    },
        "appet":{
        "yes":1,
        "poor": 0,
    },
        "pe":{
        "yes":1,
        "poor":0,
    },
        "ane":{
        "yes":1,
        "no":0,
    },
        "sg":{
        "a":0,
        "b":1,
        "c":2,
        "d":3,
        "e":4,
        }
}

In [6]:
dataset=dataset.replace(dictonary)

In [7]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,2,3,0,0,1,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1
1,3,76.459948,2,2,0,0,0,0,0,148.112676,...,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1
2,4,76.459948,0,1,0,0,0,0,0,99.000000,...,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1
3,5,76.459948,3,1,0,0,0,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1
4,5,50.000000,2,0,0,0,0,0,0,148.112676,...,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,0,0,0,0,0,0,0,219.000000,...,37.000000,9800.000000,4.400000,0,0,0,1,0,0,1
395,97,70.000000,2,0,2,0,0,0,0,220.000000,...,27.000000,8408.191126,4.705597,1,1,0,1,0,1,1
396,98,70.000000,2,3,0,0,0,0,0,110.000000,...,26.000000,9200.000000,3.400000,1,1,0,0,0,0,1
397,99,90.000000,0,0,0,0,0,0,0,207.000000,...,38.868902,8408.191126,4.705597,1,1,0,1,0,1,1
398,99,80.000000,0,0,0,0,0,0,0,100.000000,...,53.000000,8500.000000,4.900000,0,0,0,1,0,0,0

In [8]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'Possible'],
      dtype='object')

In [9]:
dataset["Possible"].value_counts()

Possible
1    249
0    150
Name: count, dtype: int64

In [10]:
indep=dataset[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane',]]
dep=dataset['Possible']

In [11]:
indep.shape

(399, 24)

In [12]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: Possible, Length: 399, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(indep,dep,test_size=0.30,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier

param_grid = { 
    'criterion':['friedman_mse', 'squared_error'],
    'n_estimators': [50, 100],  
    'max_features': ['sqrt', 'log2', None]
}


# Create GridSearchCV with the classifier instance and parameter grid
grid = GridSearchCV(GradientBoostingClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1')

# Fit the grid search
grid.fit(X_train, Y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(estimator=GradientBoostingClassifier(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'max_features': ['sqrt', 'log2', None],
                         'n_estimators': [50, 100]},
             scoring='f1', verbose=3)

In [18]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)

In [19]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[45  0]
 [ 0 75]]

In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        75

    accuracy                           1.00       120
   macro avg       1.00      1.00      1.00       120
weighted avg       1.00      1.00      1.00       120

In [22]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'n_estimators': 50}: 1.0

In [23]:
from sklearn.metrics import roc_auc_score

roc_auc_score(Y_test,grid.predict_proba(X_test)[:,1])

1.0

In [24]:
table=pd.DataFrame.from_dict(re)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.217930,0.060145,0.006892,0.008501,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",1.000000,0.972222,0.985507,0.971429,1.000000,0.985832,0.012604,5
1,0.228141,0.007655,0.006251,0.007655,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",1.000000,0.972222,0.985507,0.971429,1.000000,0.985832,0.012604,5
2,0.152081,0.047833,0.006509,0.007982,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",1.000000,0.972222,1.000000,0.971429,1.000000,0.988730,0.013805,1
3,0.442954,0.148917,0.004740,0.006276,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.985507,0.972222,1.000000,0.971429,1.000000,0.985832,0.012604,5
4,0.307175,0.110221,0.009379,0.007658,friedman_mse,None,50,"{'criterion': 'friedman_mse', 'max_features': ...",1.000000,0.985915,0.906250,0.957746,1.000000,0.969982,0.035405,11
5,0.630016,0.063918,0.004777,0.006734,friedman_mse,None,100,"{'criterion': 'friedman_mse', 'max_features': ...",1.000000,0.972222,0.970588,0.971429,0.985075,0.979863,0.011386,9
6,0.172268,0.083113,0.013700,0.003849,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.972222,0.985507,0.971429,1.000000,0.985832,0.012604,5
7,0.427621,0.084747,0.013944,0.003964,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.972222,1.000000,0.971429,1.000000,0.988730,0.013805,1
8,0.182731,0.052642,0.009791,0.008031,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.985915,0.985507,0.971429,1.000000,0.988570,0.010692,4
9,0.281467,0.023239,0.005354,0.006709,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.972222,1.000000,0.971429,1.000000,0.988730,0.013805,1
10,0.245206,0.017114,0.003125,0.006250,squared_error,None,50,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.985915,0.906250,0.957746,1.000000,0.969982,0.035405,11
11,0.474656,0.006617,0.009376,0.007656,squared_error,None,100,"{'criterion': 'squared_error', 'max_features':...",1.000000,0.972222,0.970588,0.971429,0.985075,0.979863,0.011386,9

In [ ]:
Age_input=float(input("Age:"))
BMI_input=float(input("BMI:"))
Child_input=float(input("Children:"))
Gender_input=int(input("Sex Male 0 or 1:"))
Smoker_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
F_Prediction=grid.predict([[Age_input,BMI_input,Child_input,Gender_input,Smoker_input]])
print("Future_Prediction={}".format(F_Prediction))