In [27]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
# Reading the Dataset
dataset = pd.read_csv('Chronic kidney disease prediction.csv')

In [29]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,97,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,98,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,99,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,99,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [30]:
#it replaces 'yes' with 1 and 'no' with 0.
dataset['Possible'] = dataset['Possible'].replace(['yes','no'], [1,0])

In [31]:
dictonary = {
        "rbc": {
        "abnormal":1,
        "normal": 0,
    },
        "pc":{
        "abnormal":1,
        "normal": 0,
    },
        "pcc":{
        "present":1,
        "notpresent":0,
    },
        "ba":{
        "notpresent":0,
        "present": 1,
    },
        "htn":{
        "yes":1,
        "no": 0,
    },
        "dm":{
        "yes":1,
        "no":0,
    },
        "cad":{
        "yes":1,
        "no": 0,
    },
        "appet":{
        "yes":1,
        "poor": 0,
    },
        "pe":{
        "yes":1,
        "poor":0,
    },
        "ane":{
        "yes":1,
        "no":0,
    },
        "sg":{
        "a":0,
        "b":1,
        "c":2,
        "d":3,
        "e":4,
        }
}

In [32]:
dataset=dataset.replace(dictonary)

In [33]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,2,3,0,0,1,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1
1,3,76.459948,2,2,0,0,0,0,0,148.112676,...,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1
2,4,76.459948,0,1,0,0,0,0,0,99.000000,...,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1
3,5,76.459948,3,1,0,0,0,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1
4,5,50.000000,2,0,0,0,0,0,0,148.112676,...,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,0,0,0,0,0,0,0,219.000000,...,37.000000,9800.000000,4.400000,0,0,0,1,0,0,1
395,97,70.000000,2,0,2,0,0,0,0,220.000000,...,27.000000,8408.191126,4.705597,1,1,0,1,0,1,1
396,98,70.000000,2,3,0,0,0,0,0,110.000000,...,26.000000,9200.000000,3.400000,1,1,0,0,0,0,1
397,99,90.000000,0,0,0,0,0,0,0,207.000000,...,38.868902,8408.191126,4.705597,1,1,0,1,0,1,1
398,99,80.000000,0,0,0,0,0,0,0,100.000000,...,53.000000,8500.000000,4.900000,0,0,0,1,0,0,0

In [34]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'Possible'],
      dtype='object')

In [35]:
indep=dataset[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane',]]
dep=dataset['Possible']

In [36]:
indep

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,2,76.459948,2,3,0,0,1,0,0,148.112676,...,12.518156,38.868902,8408.191126,4.705597,0,0,0,1,1,0
1,3,76.459948,2,2,0,0,0,0,0,148.112676,...,10.700000,34.000000,12300.000000,4.705597,0,0,0,1,0,0
2,4,76.459948,0,1,0,0,0,0,0,99.000000,...,12.000000,34.000000,8408.191126,4.705597,0,0,0,1,0,0
3,5,76.459948,3,1,0,0,0,0,0,148.112676,...,8.100000,38.868902,8408.191126,4.705597,0,0,0,1,0,1
4,5,50.000000,2,0,0,0,0,0,0,148.112676,...,11.800000,36.000000,12400.000000,4.705597,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,0,0,0,0,0,0,0,219.000000,...,12.500000,37.000000,9800.000000,4.400000,0,0,0,1,0,0
395,97,70.000000,2,0,2,0,0,0,0,220.000000,...,8.700000,27.000000,8408.191126,4.705597,1,1,0,1,0,1
396,98,70.000000,2,3,0,0,0,0,0,110.000000,...,9.100000,26.000000,9200.000000,3.400000,1,1,0,0,0,0
397,99,90.000000,0,0,0,0,0,0,0,207.000000,...,8.500000,38.868902,8408.191126,4.705597,1,1,0,1,0,1
398,99,80.000000,0,0,0,0,0,0,0,100.000000,...,16.300000,53.000000,8500.000000,4.900000,0,0,0,1,0,0

In [37]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: Possible, Length: 399, dtype: int64

In [38]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [40]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

param_grid = {'criterion':['gini','entropy','log_loss'],
              'max_features': [None,'sqrt','log2'],
              'n_estimators':[10,100]} 



grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [41]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [42]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[51  0]
 [ 0 82]]

In [43]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        51
           1       1.00      1.00      1.00        82

    accuracy                           1.00       133
   macro avg       1.00      1.00      1.00       133
weighted avg       1.00      1.00      1.00       133

In [44]:
print(grid.best_params_)

{'criterion': 'log_loss', 'max_features': 'sqrt', 'n_estimators': 100}

In [45]:
#if you want chech f1 score use this
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'log_loss', 'max_features': 'sqrt', 'n_estimators': 100}: 1.0

In [46]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

0.8640602582496413

In [47]:
table=pd.DataFrame.from_dict(re)

In [48]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.050005,0.006250,0.003124,6.248951e-03,gini,None,10,"{'criterion': 'gini', 'max_features': None, 'n...",0.970588,0.985507,0.984615,0.942857,0.969697,0.970653,0.015422,16
1,0.490660,0.058967,0.031251,2.078485e-06,gini,None,100,"{'criterion': 'gini', 'max_features': None, 'n...",0.985507,0.985507,0.968750,0.942857,0.985075,0.973539,0.016636,13
2,0.040628,0.007657,0.006251,7.655707e-03,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.985075,0.970588,0.918033,0.985075,1.000000,0.971754,0.028425,15
3,0.418779,0.018223,0.034377,6.250787e-03,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.971429,0.984615,0.969697,1.000000,0.985148,0.013179,4
4,0.043754,0.006251,0.015626,1.457282e-06,gini,log2,10,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,2
5,0.387526,0.011694,0.031253,9.488940e-07,gini,log2,100,"{'criterion': 'gini', 'max_features': 'log2', ...",1.000000,0.971429,0.984615,0.985075,1.000000,0.988224,0.010792,2
6,0.056255,0.007654,0.012500,6.250143e-03,entropy,None,10,"{'criterion': 'entropy', 'max_features': None,...",0.985507,0.985507,0.968750,0.942857,1.000000,0.976524,0.019526,11
7,0.534410,0.015311,0.031253,1.559775e-06,entropy,None,100,"{'criterion': 'entropy', 'max_features': None,...",1.000000,0.985507,0.968750,0.942857,0.985075,0.976438,0.019487,12
8,0.043754,0.006250,0.006251,7.655648e-03,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.985507,0.984615,0.969697,0.985075,0.984979,0.009587,8
9,0.400027,0.007656,0.034377,6.251216e-03,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",1.000000,0.971429,0.984615,0.969697,1.000000,0.985148,0.013179,4
10,0.043753,0.006249,0.015627,8.064048e-07,entropy,log2,10,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.956522,0.984615,0.985075,0.985075,0.982257,0.014132,9
11,0.403152,0.006251,0.037503,7.655862e-03,entropy,log2,100,"{'criterion': 'entropy', 'max_features': 'log2...",1.000000,0.971429,0.984615,0.969697,1.000000,0.985148,0.013179,4
12,0.059380,0.006250,0.006249,7.653955e-03,log_loss,None,10,"{'criterion': 'log_loss', 'max_features': None...",1.000000,0.970588,0.935484,0.942857,0.985075,0.966801,0.024513,18
13,0.540661,0.015937,0.031252,2.329192e-06,log_loss,None,100,"{'criterion': 'log_loss', 'max_features': None...",1.000000,0.971429,0.952381,0.942857,0.985075,0.970348,0.020861,17
14,0.037502,0.007654,0.009376,7.655824e-03,log_loss,sqrt,10,"{'criterion': 'log_loss', 'max_features': 'sqr...",0.985075,0.971429,0.968750,0.969697,1.000000,0.978990,0.012057,10
15,0.331272,0.022965,0.031252,8.996946e-07,log_loss,sqrt,100,"{'criterion': 'log_loss', 'max_features': 'sqr...",1.000000,0.971429,1.000000,0.969697,1.000000,0.988225,0.014432,1
16,0.043754,0.006251,0.006251,7.655648e-03,log_loss,log2,10,"{'criterion': 'log_loss', 'max_features': 'log...",0.969697,0.970588,0.935484,0.984615,1.000000,0.972077,0.021372,14
17,0.381274,0.018750,0.031253,1.548069e-06,log_loss,log2,100,"{'criterion': 'log_loss', 'max_features': 'log...",1.000000,0.971429,0.984615,0.969697,1.000000,0.985148,0.013179,4

In [50]:
import pickle

In [51]:
filename = "CKD_Finalized_RF_Model.sav"
pickle.dump(grid, open(filename, 'wb'))

In [52]:
model = pickle.load(open("CKD_Finalized_RF_Model.sav",'rb'))

In [53]:
Future_Prediction=model.predict([[ 6, 60, 2, 4, 0, 0, 0, 0, 1, 94, 67, 1,135, 4.9, 9.9, 30, 16700, 4.8, 0,0,0,0,0 ,0]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]