In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Chronic kidney disease prediction.csv')

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,c,3,0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3,76.459948,c,2,0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4,76.459948,a,1,0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5,76.459948,d,1,0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5,50.000000,c,0,0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,a,0,0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,97,70.000000,c,0,2,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,98,70.000000,c,3,0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,99,90.000000,a,0,0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,99,80.000000,a,0,0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
#it replaces 'yes' with 1 and 'no' with 0.
dataset['Possible'] = dataset['Possible'].replace(['yes','no'], [1,0])

In [5]:
dictonary = {
        "rbc": {
        "abnormal":1,
        "normal": 0,
    },
        "pc":{
        "abnormal":1,
        "normal": 0,
    },
        "pcc":{
        "present":1,
        "notpresent":0,
    },
        "ba":{
        "notpresent":0,
        "present": 1,
    },
        "htn":{
        "yes":1,
        "no": 0,
    },
        "dm":{
        "yes":1,
        "no":0,
    },
        "cad":{
        "yes":1,
        "no": 0,
    },
        "appet":{
        "yes":1,
        "poor": 0,
    },
        "pe":{
        "yes":1,
        "poor":0,
    },
        "ane":{
        "yes":1,
        "no":0,
    },
        "sg":{
        "a":0,
        "b":1,
        "c":2,
        "d":3,
        "e":4,
        }
}

In [6]:
dataset=dataset.replace(dictonary)

In [7]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,Possible
0,2,76.459948,2,3,0,0,1,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1
1,3,76.459948,2,2,0,0,0,0,0,148.112676,...,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1
2,4,76.459948,0,1,0,0,0,0,0,99.000000,...,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1
3,5,76.459948,3,1,0,0,0,0,0,148.112676,...,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1
4,5,50.000000,2,0,0,0,0,0,0,148.112676,...,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,97,70.000000,0,0,0,0,0,0,0,219.000000,...,37.000000,9800.000000,4.400000,0,0,0,1,0,0,1
395,97,70.000000,2,0,2,0,0,0,0,220.000000,...,27.000000,8408.191126,4.705597,1,1,0,1,0,1,1
396,98,70.000000,2,3,0,0,0,0,0,110.000000,...,26.000000,9200.000000,3.400000,1,1,0,0,0,0,1
397,99,90.000000,0,0,0,0,0,0,0,207.000000,...,38.868902,8408.191126,4.705597,1,1,0,1,0,1,1
398,99,80.000000,0,0,0,0,0,0,0,100.000000,...,53.000000,8500.000000,4.900000,0,0,0,1,0,0,0

In [8]:
dataset.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'Possible'],
      dtype='object')

In [9]:
dataset["Possible"].value_counts()

Possible
1    249
0    150
Name: count, dtype: int64

In [10]:
indep=dataset[['age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr', 'bu',
       'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane',]]
dep=dataset['Possible']

In [11]:
indep.shape

(399, 24)

In [12]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: Possible, Length: 399, dtype: int64

In [13]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [26]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133

[[51  0]
 [ 6 76]]

In [29]:
roc_auc = roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 1.0

In [30]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.68      0.98      0.81        51
           1       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

[[50  1]
 [23 59]]

In [31]:
roc_auc = roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 0.9017216642754664

In [32]:
from sklearn.naive_bayes import BernoulliNB
classifier = BernoulliNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.84      1.00      0.91        51
           1       1.00      0.88      0.94        82

    accuracy                           0.92       133
   macro avg       0.92      0.94      0.92       133
weighted avg       0.94      0.92      0.93       133

[[51  0]
 [10 72]]

In [33]:
roc_auc = roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 0.9774031563845051

In [42]:
from sklearn.naive_bayes import ComplementNB
classifier =ComplementNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, y_pred)              
print(clf_report)
print(cm)

              precision    recall  f1-score   support

           0       0.68      0.98      0.81        51
           1       0.98      0.72      0.83        82

    accuracy                           0.82       133
   macro avg       0.83      0.85      0.82       133
weighted avg       0.87      0.82      0.82       133

[[50  1]
 [23 59]]

In [43]:
roc_auc = roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])
print("ROC AUC Score:", roc_auc)

ROC AUC Score: 0.9017216642754664

In [50]:
Future_Prediction=classifier.predict([[ 6, 60, 2, 4, 0, 0, 0, 0, 1, 94, 67, 1,135, 4.9, 9.9, 30, 16700, 4.8, 0,0,0,0,0 ,0]])
print("Future_Prediction={}".format(Future_Prediction))

C:\Users\ELCOT\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but CategoricalNB was fitted with feature names
  warnings.warn(

Future_Prediction=[1]